package com.dassmeta.weixin.common.dal.dataobject;

public class ExpressQueryResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_query_result.id
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_query_result.message
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_query_result.no
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_query_result.ischeck
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    private String ischeck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_query_result.com
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    private String com;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_query_result.status
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_query_result.condition
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    private String condition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_query_result.state
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_query_result.data
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_query_result.id
     *
     * @return the value of express_query_result.id
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_query_result.id
     *
     * @param id the value for express_query_result.id
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_query_result.message
     *
     * @return the value of express_query_result.message
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_query_result.message
     *
     * @param message the value for express_query_result.message
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_query_result.no
     *
     * @return the value of express_query_result.no
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_query_result.no
     *
     * @param no the value for express_query_result.no
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_query_result.ischeck
     *
     * @return the value of express_query_result.ischeck
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public String getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_query_result.ischeck
     *
     * @param ischeck the value for express_query_result.ischeck
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public void setIscheck(String ischeck) {
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_query_result.com
     *
     * @return the value of express_query_result.com
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public String getCom() {
        return com;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_query_result.com
     *
     * @param com the value for express_query_result.com
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public void setCom(String com) {
        this.com = com;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_query_result.status
     *
     * @return the value of express_query_result.status
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_query_result.status
     *
     * @param status the value for express_query_result.status
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_query_result.condition
     *
     * @return the value of express_query_result.condition
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_query_result.condition
     *
     * @param condition the value for express_query_result.condition
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public void setCondition(String condition) {
        this.condition = condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_query_result.state
     *
     * @return the value of express_query_result.state
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_query_result.state
     *
     * @param state the value for express_query_result.state
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_query_result.data
     *
     * @return the value of express_query_result.data
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_query_result.data
     *
     * @param data the value for express_query_result.data
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    public void setData(String data) {
        this.data = data;
    }
}