package com.dassmeta.weixin.common.dal.dataobject;

import com.dassmeta.weixin.common.dal.dataobject.ExpressQueryResult;
import com.dassmeta.weixin.common.dal.dataobject.ExpressQueryResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpressQueryResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_query_result
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    int countByExample(ExpressQueryResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_query_result
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    int deleteByExample(ExpressQueryResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_query_result
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_query_result
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    int insert(ExpressQueryResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_query_result
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    int insertSelective(ExpressQueryResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_query_result
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    List<ExpressQueryResult> selectByExample(ExpressQueryResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_query_result
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    ExpressQueryResult selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_query_result
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") ExpressQueryResult record, @Param("example") ExpressQueryResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_query_result
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    int updateByExample(@Param("record") ExpressQueryResult record, @Param("example") ExpressQueryResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_query_result
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    int updateByPrimaryKeySelective(ExpressQueryResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express_query_result
     *
     * @mbggenerated Sun Nov 08 20:50:53 CST 2015
     */
    int updateByPrimaryKey(ExpressQueryResult record);
}